### ISSUE TITLE
Webpack 4: DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by Xotic750** [lodash/lodash-webpack-plugin#146]
Problem code (I believe):

```
      compiler.plugin('normal-module-factory', (nmf) => {
        nmf.plugin('after-resolve', (data, callback) => {
          if (data) {
            data.resource = resolve(data)
            return callback(null, data)
          }
          return callback()
        })
      })
```

From log:

```
Grahams-MBP:Byxelkrok grahamfairweather$ node --trace-deprecation ./node_modules/.bin/webpack
(node:90696) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at LodashModuleReplacementPlugin.apply (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/lodash-webpack-plugin/lib/index.js:88:16)
    at webpack (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/webpack-cli/bin/webpack.js:510:3)
    at Object.parse (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/webpack-cli/node_modules/yargs/yargs.js:543:18)
    at /Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/webpack/bin/webpack.js:12:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Possible solution:

```
if (compiler.hooks) {
  ...
} else {
  ...
}
```

**Comment by Xotic750** [comment]
Apoologies, didn't see the PR https://github.com/lodash/lodash-webpack-plugin/pull/142
