### ISSUE TITLE
predicate is not a function at baseFindIndex

### ISSUE THREAD

**Issue by viveleroi** [lodash/lodash-webpack-plugin#66]
In testing this on [a project](https://github.com/helion3/inspire-tree/tree/lodash-webpack-plugin) already using the lodash bundle plugin, something is causing the final output to break on me, throwing this error:

```
TypeError: predicate is not a function at baseFindIndex (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:7055:10) at findIndex (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:7028:11)
at http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:7141:18
at VCache.VArrayDirtyCompare [as cmpFn] (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:14083:36)
at VCache.render (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:14035:56)
at renderThunk (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:12764:46)
at handleThunk (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:12747:22)
at thunks (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:12370:18)
at walk (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:12249:10)
at diff (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:12236:6)
at InspireDOM.renderNodes (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:12049:53)
at InspireDOM.applyChanges (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:11036:19)
at http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:5696:41
at initializePromise (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:7816:8)
at new Promise (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:8228:34)
at TreeNode.expand (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:5683:21)
at TreeNode.toggleCollapse (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:6536:46)
at HTMLAnchorElement.onclick (http://127.0.0.1/inspire-tree/dist/inspire-tree-bundled.js:11711:31
```

When compiled without this new plugin, everything works as expected. 

A paste of the compiled output file:
http://pastebin.com/LwJ3DT4L

**Comment by jdalton** [comment]
It looks like you're using "shorthands" be sure to enable that featureset.

**Comment by D7Torres** [comment]
If I may help someone blindly coming from Google with the same issue, you need to write this in your webpack.config.js:
```
new LodashModuleReplacementPlugin({
  shorthands: true
});
```
explained in the repo doc: https://github.com/lodash/lodash-webpack-plugin
